### ISSUE TITLE
Assert error

### ISSUE THREAD

**Issue by schmiph2** [SRPOL-AUI/storir#4] opened 2021-09-29 11:02 UTC
Hi 

Thank you for publishing storir. I just tested the example.py and got an assertion error:

~/.local/lib/python3.6/site-packages/storir/rir_utils.py in thin_out_reflections(y, start_idx, end_idx, rate)
     33     ray_indices = [idx for idx in range(start_idx, end_idx + 1) if y[idx] != 0]
     34     num_rays = int(len(ray_indices) * rate)
---> 35     assert num_rays >= 1
     36     random_subset = np.random.choice(ray_indices, num_rays, replace=False)
     37     y[random_subset] = 0

AssertionError: 

Can you help me?

**Comment by masztalskipiotr** [comment] 2024-03-13 15:18
Two years later, but the problem is fixed now. The assert statement was not necessary.

**Closed as completed by masztalskipiotr** 2024-03-13 15:18 UTC
